"""Generates src/sdk_params.c: the NONOS SDK's system parameter sectors with WiFi off, written
into the emulated flash when a program comes without any (see esp_default_sdk_params).

    python tools/gen_sdk_params.py flash_or_save.bin

The input is a 4 MB flash (a .sav) left by a program that called WiFi.mode(WIFI_OFF): the SDK
then stores its parameters with the mode "off" (byte 8 of the parameter sector = 0) in the
sectors 0x3FD000 / 0x3FE000 (two copies) and 0x3FF000 (which copy is current). Do not edit the
generated file.
"""
import sys

SECTORS = (0x3FD000, 0x3FE000, 0x3FF000)


def main():
    d = open(sys.argv[1], "rb").read()
    out = ["/* Generated by tools/gen_sdk_params.py: the SDK's system parameter sectors with",
           "   WiFi off. Do not edit. */",
           "#include \"esp8266.h\"", "", "",
           "const EspFlashBlock esp_sdk_params[] = {"]
    arrays = []
    for i, s in enumerate(SECTORS):
        blk = d[s:s + 0x1000].rstrip(b"\xff")
        if not blk:
            continue
        name = "sector%d" % i
        rows = [", ".join("0x%02x" % b for b in blk[k:k + 16]) for k in range(0, len(blk), 16)]
        arrays.append("static const uint8_t %s[%d] = {\n    %s,\n};\n" % (name, len(blk), ",\n    ".join(rows)))
        out.append("    { 0x%06Xu, %d, %s }," % (s, len(blk), name))
    out.append("};")
    out.append("const size_t esp_sdk_params_count = sizeof esp_sdk_params / sizeof esp_sdk_params[0];")
    text = "\n".join(out[:5]) + "\n" + "\n".join(arrays) + "\n" + "\n".join(out[5:]) + "\n"
    open("src/sdk_params.c", "w", newline="\n").write(text)
    print("src/sdk_params.c:", ", ".join(hex(s) for s in SECTORS))


if __name__ == "__main__":
    main()
